### ISSUE TITLE
Anti-idea: Missing the larger digital tsunami and the transformative impact on the civic arena

### ISSUE THREAD

**Issue by patwater** [codeforamerica/civic-tech-patterns#48]
Friends there's a larger game afoot... Evgeny has an ax to grind though he makes some important points here...

"The continuing collapse of public trust in Facebook is welcome news to those of us who have been warning about the perils of “data extractivism” for years.

It’s reassuring to have final, definitive proof that beneath Facebook’s highfalutin rhetoric of “building a global community that works for all of us” lies a cynical, aggressive project – of building a global data vacuum cleaner that sucks from all of us. Like others in this industry, Facebook makes money by drilling deep into our data selves – pokes and likes is simply how our data comes to the surface – much like energy firms drill deep into the oil wells: profits first, social and individual consequences later.

Furthermore, the rosy digital future – where cleverly customised ads subsidise the provision of what even Mark Zuckerberg calls “social infrastructure” – is no longer something that many of us will be taking for granted.

...

We face three political options. We can continue with the current model, with Facebook, Alphabet, Amazon and others taking over more and more functions of the state. With time, perhaps, we won’t need to worry that their technologies are used to influence elections because most of our lives will depend on what happens in their boardrooms – not on what happens in our parliaments.
Alternatively, we can opt for the kind of pseudo-antiglobalism endorsed by Bannon, reclaiming some autonomy from the tech giants by over-empowering the financial sector (which Bannon, of course, also wants to tame with cryptocurrencies; we’ll see who will tame whom, but so far banks seem to have survived – and even swallowed – their challengers).

Finally, we can use the recent data controversies to articulate a truly decentralised, emancipatory politics, whereby the institutions of the state (from the national to the municipal level) will be deployed to recognise, create, and foster the creation of social rights to data. These institutions will organise various data sets into pools with differentiated access conditions. They will also ensure that those with good ideas that have little commercial viability but promise major social impact would receive venture funding and realise those ideas on top of those data pools."
https://www.theguardian.com/technology/2018/mar/31/big-data-lie-exposed-simply-blaming-facebook-wont-fix-reclaim-private-information?CMP=Share_iOSApp_Other

**Comment by bensheldon** [comment]
@patwater thanks for sharing these great insights! Any suggestions for how to boil it down to 2-3 sentences of actionable tactic?

**Comment by patwater** [comment]
Respectfully, it's a strategic alignment, not a pithy aphorism. That said the recent shift to data-driven advocacy is good. Would be nice if there was a common platform of policies beyond just open data though

**Comment by bensheldon** [comment]
Agreed 👍
